micronaut:
  server:
    port: 8080
  application:
    name: movie rental app
  http:
    services:
      invoice:
        urls:
        - 'http://localhost:8080'

endpoints:
  health:
    details-visible: ANONYMOUS
  info:
    enabled: true
    sensitive: false

info:
  version: $project.version
  name: 'video rental service'



